//
//  WhatsAppConstants.swift
//  
//
//  Created by Junpeng Chen on 27.07.23.
//

import Foundation

struct WhatsAppConstants {
    static let chatFileName = "_chat.txt"
    
    static let autoGeneratedMessages = [
        "Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them.",
        "Messages to yourself are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them.",
        "Missed voice call.",
        "Missed video call.",
        "You deleted this message.",
        "This message was deleted.",
        "You changed this group's icon.",
        "You changed the group description."
    ]
    
    static let attachmentPrefix = "<attached: "
    static let attachmentSuffix = ">"
    
    static let viewOncePhotoText = "image omitted"
    static let viewOnceVideoText = "video omitted"
    
    static let dateFormat = "[dd.MM.yy, HH:mm:ss]"
    
    static let filePattern = #/^(.*) <attached: (.*)>$/#
    static let locationPattern = #/^(.*?) \((.*?)\):\shttps://maps\.google\.com/\?q=(-?\d+\.\d+),(-?\d+\.\d+)$/#
    static let pollPattern = #/^POLL:\n(.+)\n((?:OPTION: .+ \(\d+ vote[s]?\)\n?){2,})$/#
    static let pollOptionPattern = #/OPTION: (.+) \((\d+) votes?\)/#
}
