//
//  ChatExtractor.swift
//  
//
//  Created by Junpeng Chen on 26.07.23.
//

import Foundation

protocol ChatExtractor {
    associatedtype ChatDataType: ChatData
    
    func extractChatData() throws -> ChatDataType
    func readChatFile() throws -> [String]
    func processMessage(_ message: String) throws -> any ChatMessage
}

enum ChatExtractorError: Error {
    case attachmentNotSupported
    case autoGeneratedMessage
    case directoryNotExist
    case fileNotExist
    case messageNotValid
    case readChatFileFailed
}

extension ChatExtractorError: LocalizedError {
    var errorDescription: String? {
        switch self {
        case .attachmentNotSupported:
            return NSLocalizedString("Not suppoerted attachment is found.", comment: "Attachment Not Supported")
        case .autoGeneratedMessage:
            return NSLocalizedString("Autogenerated message is found.", comment: "Autogenerated Message Found")
        case .directoryNotExist:
            return NSLocalizedString("The directory does not exist.", comment: "Directory Not Exist")
        case .fileNotExist:
            return NSLocalizedString("The file does not exist.", comment: "File Not Exist")
        case .messageNotValid:
            return NSLocalizedString("The message is not valid.", comment: "Message Not Valid")
        case .readChatFileFailed:
            return NSLocalizedString("Failed to read chat file.", comment: "Read Chat File Failed")
        }
    }
}
